version: '3.8'

services:
  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:5000"
    ports:
      - "5020:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - part1_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

  app:
    build:
      context: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=5000"
    networks:
      - part1_network

networks:
  part1_network:
    driver: bridge

